/*
  Warnings:

  - The values [PAGAMENTO_PENDENTE,PAGAMENTO_CONFIRMADO,PAGAMENTO_RECUSADO,EM_PREPARACAO,EM_TRANSPORTE] on the enum `checkout_status` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterTable
ALTER TABLE `checkout` MODIFY `status` ENUM('ENDERECO_PENDENTE', 'ENTREGADOR_PENDENTE', 'METODO_DE_PAGAMENTO_PENDENTE', 'AGUARDANDO_PAGAMENTO', 'PAGAMENTO_COM_SUCESSO', 'PAGAMENTO_REJEITADO', 'AGUARDANDO_RETIRADA', 'EM_TRANSITO', 'ENTREGUE', 'CANCELADO') NOT NULL;
