version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wine_emporium_db
    ports:
      - 3306:3306
  mysql-test:
    image: mysql:5.7
    container_name: mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wine_emporium_db
    ports:
      - 3307:3306