service: wine-emporium

frameworkVersion: '3'

provider:
  name: aws
  region: sa-east-1
  stage: ${opt:stage, 'prd'}
  deploymentBucket:
    name: kcalixto-serverless-framework

functions:
  api:
    handler: index.handler
    runtime: nodejs18.x
    environment:
      NODE_ENV: ${self:provider.stage}
      DB_HOST: ${ssm:/wine-emporium-api/db-host}
      DB_NAME: ${ssm:/wine-emporium-api/db-name}
      DB_USER: ${ssm:/wine-emporium-api/db-user}
      DB_PASS: ${ssm:/wine-emporium-api/db-pass}
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
