service: wine-emporium

frameworkVersion: "3"

custom:
  domain:
    dev: api.dev.wineemporium.shop
    prd: api.wineemporium.shop

  customCertificate:
    certificateName: ${self:custom.domain.${self:provider.stage}}
    hostedZoneNames: ${self:custom.domain.${self:provider.stage}}.

  customDomain:
    certificateName: ${self:custom.domain.${self:provider.stage}}
    domainName: ${self:custom.domain.${self:provider.stage}}
    stage: ${self:provider.stage}
    createRoute53Record: true

provider:
  name: aws
  region: sa-east-1
  stage: ${opt:stage, 'prd'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter
            - s3:*
          Resource: "*"
  deploymentBucket:
    name: kcalixto-serverless-framework

functions:
  api:
    handler: dist/lambda.handler
    runtime: nodejs18.x
    package:
      include:
        - dist/**
        - node_modules/**
    environment:
      NODE_ENV: ${self:provider.stage}
      DATABASE_URL: ${ssm:/wine_emporium_db/db-url}
      JWT_SECRET: ${ssm:/wine-emporium-api/jwt-secret}

      PRISMA_CLI_BINARY_TARGETS: native,rhel-openssl-1.0.x
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-domain-manager
  - serverless-certificate-creator
  - serverless-dotenv-plugin
