service: wine-emporium

frameworkVersion: "3"

custom:
  domain:
    dev: api.dev.wineemporium.shop
    prd: api.wineemporium.shop

  customCertificate:
    certificateName: ${self:custom.domain.${self:provider.stage}}
    hostedZoneNames: ${self:custom.domain.${self:provider.stage}}.

  customDomain:
    certificateName: ${self:custom.domain.${self:provider.stage}}
    domainName: ${self:custom.domain.${self:provider.stage}}
    stage: ${self:provider.stage}
    createRoute53Record: true

provider:
  name: aws
  region: sa-east-1
  stage: ${opt:stage, 'prd'}
  deploymentBucket:
    name: kcalixto-serverless-framework

functions:
  api:
    handler: index.handler
    runtime: nodejs18.x
    environment:
      NODE_ENV: ${self:provider.stage}
      DB_HOST: ${ssm:/wine_emporium_db/db-host}
      DB_NAME: ${ssm:/wine_emporium_db/db-name}
      DB_USER: ${ssm:/wine_emporium_db/db-user}
      DB_PASS: ${ssm:/wine_emporium_db/db-pass}
      JWT_SECRET: ${ssm:/wine-emporium-api/jwt-secret}
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-domain-manager
  - serverless-certificate-creator
