service: wine-emporium

frameworkVersion: "3"

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packagerOptions:
      scripts:
        - prisma generate
        - find . -name "libquery_engine-*" -not -name "libquery_engine-rhel-openssl-*" | xargs rm

  domain:
    prd: api.wineemporium.shop

  customCertificate:
    certificateName: ${self:custom.domain.${self:provider.stage}}
    hostedZoneNames: ${self:custom.domain.${self:provider.stage}}.

  customDomain:
    certificateName: ${self:custom.domain.${self:provider.stage}}
    domainName: ${self:custom.domain.${self:provider.stage}}
    stage: ${self:provider.stage}
    createRoute53Record: true

provider:
  name: aws
  region: sa-east-1
  stage: ${opt:stage, 'prd'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter
            - s3:*
          Resource: "*"
  deploymentBucket:
    name: kcalixto-serverless-framework
  logRetentionInDays: 7

package:
  include:
    - dist/**
    - .env
  exclude:
    - node_modules/**

functions:
  api:
    handler: dist/lambda.handler
    runtime: nodejs18.x
    environment:
      NODE_ENV: ${self:provider.stage}
      DATABASE_URL: ${ssm:/wine_emporium_db/db-url}
      JWT_SECRET: ${ssm:/wine-emporium-api/jwt-secret}
      PRISMA_CLI_BINARY_TARGETS: native,rhel-openssl-1.0.x
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-domain-manager
  - serverless-certificate-creator
  - serverless-dotenv-plugin
  - serverless-webpack