name: V1 - 🍷 API Deploy

on:
  push:
    branches: [main, api-refact]
    paths:
      - 'api_v1/**'
      - '.github/workflows/deploy-api_v1.yml'

jobs:
  deploy:
    name: V1 - 🍷 API Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api_v1
    env:
      AWS_REGION: sa-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      STAGE: prd
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm ci
      - run: npm run test
      - run: npm i serverless -g
      - run: serverless create-cert --stage ${{ env.STAGE }} --verbose
      - run: serverless create_domain --stage ${{ env.STAGE }} --verbose
      - run: serverless deploy --stage ${{ env.STAGE }} --verbose
